import { readdirSync, readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { join, basename } from "node:path";
import { loadConfig, fail } from "./lib.mjs";

const ROLES = ["orchestrator", "product", "implementer", "qa"];
const OPEN_RE = /<!--\s*brief:([a-z-,\s]+?)\s*-->/g;
const CLOSE_TAG = "<!-- /brief -->";

/**
 * Extracts a document's brief-tagged blocks, guarding against nesting.
 *
 * @param source - document path, for error messages
 * @param text - document content
 * @returns the blocks with their target roles
 */
function extractBlocks(source, text) {
  const blocks = [];
  let match;
  OPEN_RE.lastIndex = 0;
  while ((match = OPEN_RE.exec(text)) !== null) {
    const roles = match[1].split(",").map((r) => r.trim()).filter(Boolean);
    const start = match.index + match[0].length;
    const end = text.indexOf(CLOSE_TAG, start);
    if (end === -1) fail(`${source}: unclosed brief tag at offset ${match.index}`);
    if (text.slice(start, end).includes("<!-- brief:")) {
      fail(`${source}: brief tag nested inside the block opened at offset ${match.index}`);
    }
    for (const role of roles) {
      if (!ROLES.includes(role)) fail(`${source}: unknown role "${role}"`);
    }
    blocks.push({ roles, content: text.slice(start, end).trim() });
    OPEN_RE.lastIndex = end + CLOSE_TAG.length;
  }
  return blocks;
}

/**
 * Compiles one brief per role from the tagged documents and the config.
 *
 * Each brief opens on the profile's command table, then stacks the sections
 * tagged for that role, in directory order then file order. In --check mode
 * it compares without writing, exiting 1 on drift.
 */
function main() {
  const checkMode = process.argv.includes("--check");
  const config = loadConfig();
  const perRole = Object.fromEntries(ROLES.map((r) => [r, []]));

  for (const dir of config.docs_dirs) {
    if (!existsSync(dir)) fail(`repertoire de documents not found: ${dir}`);
    for (const file of readdirSync(dir).filter((f) => f.endsWith(".md")).sort()) {
      const text = readFileSync(join(dir, file), "utf8");
      for (const block of extractBlocks(join(dir, file), text)) {
        for (const role of block.roles) {
          perRole[role].push({ source: basename(file), content: block.content });
        }
      }
    }
  }

  const commandsSection = [
    "## Commandes du projet",
    "",
    `Profile: ${config.profile}. When a rule or a prompt names a command by its key (check, lint, test_unit, audit...), the command below is the one it faut executer.`,
    "",
    ...Object.entries(config.commands).map(([key, cmd]) => `- ${key} : \`${cmd}\``),
  ].join("\n");

  let drift = false;
  for (const role of ROLES) {
    const sections = perRole[role].map((b) => `## Source : ${b.source}\n\n${b.content}`).join("\n\n");
    const output = [
      `# Brief compile : ${role}`,
      "",
      "GENERATED by agent-pipeline/scripts/sync-briefs.mjs. Do not edit.",
      "En cas de doute ou de conflit, le document source fait foi.",
      "",
      commandsSection,
      "",
      sections,
      "",
    ].join("\n");
    const outPath = join(config.briefs_dir, `${role}.md`);
    if (checkMode) {
      const current = existsSync(outPath) ? readFileSync(outPath, "utf8") : "";
      if (current !== output) {
        console.error(`out of sync: ${outPath}`);
        drift = true;
      }
    } else {
      mkdirSync(config.briefs_dir, { recursive: true });
      writeFileSync(outPath, output);
      console.log(`written: ${outPath} (${perRole[role].length} sections)`);
    }
  }
  if (checkMode && drift) fail("Briefs out of sync. Run the build.");
  if (checkMode) console.log("Briefs in sync.");
}

main();
